"""Streamlit chat interface. Launched via ``streamlit run app.py`` from the repository root."""

from __future__ import annotations

import logging

import streamlit as st

from indiantaxgpt import __version__
from indiantaxgpt.assistant import (
    NO_CONTEXT_ANSWER,
    Source,
    TaxAssistant,
    build_assistant,
    to_sources,
)
from indiantaxgpt.config import ConfigError, Settings

logger = logging.getLogger(__name__)

EXAMPLE_QUESTIONS = [
    "What deductions can I claim under Section 80C?",
    "How is income from house property taxed?",
    "Who is required to file an income tax return?",
    "What is the due date for paying advance tax?",
]

DISCLAIMER = (
    "IndianTaxGPT summarises the documents it has indexed and can be wrong or out of date. "
    "It is not tax advice. Check the cited source, and consult a chartered accountant "
    "for decisions about your own return."
)

SETUP_HELP = """\
**To get started:**
1. Copy `.env.example` to `.env` and set `PINECONE_API_KEY`.
2. Download a model: `python -m indiantaxgpt.download_model`
3. Put tax PDFs in `data/` and run `python -m indiantaxgpt.ingest`
4. Restart this app.
"""


@st.cache_resource(show_spinner="Loading the model and connecting to the knowledge base…")
def get_assistant() -> TaxAssistant:
    return build_assistant(Settings.from_env())


def render_sources(sources: list[Source]) -> None:
    if not sources:
        return
    with st.expander(f"Sources ({len(sources)})"):
        for source in sources:
            st.markdown(f"**{source.label}**")
            st.caption(source.excerpt)


def render_sidebar(settings: Settings | None) -> None:
    with st.sidebar:
        st.header("About")
        st.write(
            "Ask questions about Indian income tax. Answers are generated by a local "
            "Llama 2 model from passages retrieved out of your indexed tax documents."
        )
        if settings is not None:
            st.subheader("Configuration")
            st.markdown(
                f"- Model: `{settings.llm_model_path.name}`\n"
                f"- Index: `{settings.pinecone_index_name}`\n"
                f"- Passages per answer: `{settings.retriever_k}`"
            )
        if st.button("Clear conversation", width="stretch"):
            st.session_state.messages = []
            st.rerun()
        st.divider()
        st.caption(DISCLAIMER)
        st.caption(f"v{__version__}")


def render_examples() -> None:
    st.markdown("Try one of these:")
    columns = st.columns(2)
    for i, question in enumerate(EXAMPLE_QUESTIONS):
        if columns[i % 2].button(question, key=f"example-{i}", width="stretch"):
            st.session_state.pending_question = question
            st.rerun()


def answer(assistant: TaxAssistant, question: str) -> dict:
    """Answer ``question`` inside the current chat bubble and return the message to store."""
    try:
        with st.spinner("Searching tax documents…"):
            docs = assistant.retrieve(question)
        if not docs:
            st.markdown(NO_CONTEXT_ANSWER)
            return {"role": "assistant", "content": NO_CONTEXT_ANSWER, "sources": []}

        text = st.write_stream(assistant.stream_answer(question, docs))
        sources = to_sources(docs)
        render_sources(sources)
        return {"role": "assistant", "content": str(text).strip(), "sources": sources}
    except Exception:
        logger.exception("Failed to answer question")
        message = "Something went wrong while generating the answer. Check the logs and try again."
        st.error(message)
        return {"role": "assistant", "content": message, "sources": []}


def main() -> None:
    st.set_page_config(page_title="IndianTaxGPT", page_icon="📚", layout="centered")
    st.session_state.setdefault("messages", [])

    try:
        settings = Settings.from_env()
    except ConfigError as exc:
        render_sidebar(None)
        st.error(str(exc))
        st.stop()

    render_sidebar(settings)
    st.title("IndianTaxGPT")
    st.caption("Answers to Indian income tax questions, with the passages they came from.")

    try:
        assistant = get_assistant()
    except ConfigError as exc:
        st.error(str(exc))
        st.markdown(SETUP_HELP)
        st.stop()

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            render_sources(message.get("sources", []))

    question = st.chat_input("Ask a question about Indian income tax")
    question = question or st.session_state.pop("pending_question", None)

    if not question and not st.session_state.messages:
        render_examples()
        return
    if not question:
        return

    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)
    with st.chat_message("assistant"):
        st.session_state.messages.append(answer(assistant, question))
